% defines of in which column is what type of data
M_RAW = 1;
M_SHIFT_BY_MAX = 2;
M_SHIFT_BY_CALIB = 3;
M_SCALE_BY_CALIB = 4;
M_SCALE_TO_FILTER_A = 5;
M_SCALE_TO_FILTER_B = 6;
M_SCALE_TO_FILTER_C = 7;
M_SCALE_TO_CALIB_A = 8;
M_SCALE_TO_CALIB_B = 9;

M_NAMES = {'No compensation'; ...
    'Shift to max readed value'; ...
    'Shift to calibrated value'; ...
    'Scale by calibrated value'; ...
    'Scale to preset filter A'; ...
    'Scale to preset filter B'; ...
    'Scale to preset filter C'; ...
    'Scale to preset calibration multiplier A'; ...
    'Scale to preset calibration multiplier B'; ...
    };

% path to data folder
PATH = "data\";
